import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import authRoutes from './routes/auth.js';
import usersRoutes from './routes/users.js';
import providersRoutes from './routes/providers.js';
import pagesRoutes from './routes/pages.js';
import websitesRoutes from './routes/websites.js';
import skillsRoutes from './routes/skills.js';
import postsRoutes from './routes/posts.js';
import jobsRoutes from './routes/jobs.js';
import notificationsRoutes from './routes/notifications.js';
import activityRoutes from './routes/activity.js';
import uploadRoutes from './routes/upload.js';
import mediaRoutes from './routes/media.js';
import settingsRoutes from './routes/settings.js';
import groupPostsRoutes from './routes/groupPosts.js';
import groupCategoriesRoutes from './routes/groupCategories.js';
import driveAuthRoutes from './routes/driveAuth.js';
import userAuthRoutes from './routes/userAuth.js';
import userSyncRoutes from './routes/userSync.js';
import { activityLogger } from './middleware/activityLog.js';
import { syncApiLimiter } from './middleware/rateLimit.js';
import { getMediaStorageMode, isUsingGoogleDrive } from './services/mediaStorage.js';
import {
  backfillProviderMetadata,
  seedProviderTemplates,
} from './services/providerTemplateService.js';
import { loadAppSettings } from './services/appSettingsService.js';
import { ensureUserPagesTables, ensurePageSkillsTable, ensureContentTopicsRepeatDaily, ensureContentTopicsLastRun, ensureSkillsTypeColumn, ensureUsersUsernameColumn, ensurePostsFbMediaIds, ensurePostsAutoGenerateImage, ensurePostsSaveImageLocal, ensurePostsAutoGenerateDefaultTrue, ensureGeminiImageGenerateContent, ensure9RouterImageModel, ensurePostsPublishingStatus, ensureImageScheduleDb, ensureImageSchedulePerUser, ensurePageImageSchedule, ensureUtf8mb4TextColumns, ensureAppSettingsTable, ensureFbPagesComposio, ensureFbPagesDriveFolder, ensureGroupPostsTables, ensureGroupPostDraftsTable, ensureGroupPostNameSharedDrafts, ensureGroupPostClientSyncs, ensureDriveOAuthMigration, ensurePostsPlatformPostType, ensureWebsitesTable, ensurePostsWebsiteColumns, ensureGroupPostsFbUrl, ensureUserAccountsTable, ensureLicenseKeysTable, ensureUserPostsTable, ensureUserAccountsMergedIntoUsers, ensureUserActivityLogTable, ensureUserPostsUpdatedAt, ensureUserPostsMergedGroupPosts, ensureGroupPostDraftsSharedIndex, ensureUserPostsPendingApproval, ensureUserPostsCorrectUniqueKey, ensureUsersPhone, ensureLicenseKeyDevices, ensureUserActivityLogAuthor, ensureGroupPostCategories, ensureUserPostCategories, ensureGroupPostDraftsCategory } from './services/migrationRunner.js';
import { startScheduler } from './services/scheduler.js';
import { getDbCharsetInfo } from './db.js';

dotenv.config();

// Bảo mật: JWT_SECRET có giá trị fallback mặc định ('replace_with_strong_secret') rải ở nhiều file để
// dev chạy được ngay. Nếu deploy production mà quên đặt secret thật, bất kỳ ai cũng tự ký được token
// super_admin. Chặn khởi động luôn thay vì âm thầm chạy với secret ai cũng biết.
if (process.env.NODE_ENV === 'production'
    && (!process.env.JWT_SECRET || process.env.JWT_SECRET === 'replace_with_strong_secret')) {
  console.error('FATAL: JWT_SECRET chưa được đặt (hoặc còn là giá trị mặc định) khi NODE_ENV=production. '
    + 'Đặt JWT_SECRET mạnh trong backend/.env rồi khởi động lại.');
  process.exit(1);
}

const app = express();
// Cần để req.protocol đọc đúng https khi chạy sau nginx reverse proxy (X-Forwarded-Proto) —
// dùng để tự detect redirect URI cho Google Drive OAuth2 (routes/driveAuth.js).
app.set('trust proxy', 1);
const port = process.env.PORT || 3001;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const publicPath = path.resolve(__dirname, '../../public');

app.use(cors());
const bodyLimit = process.env.JSON_BODY_LIMIT || '15mb';
app.use(express.json({ limit: bodyLimit }));
app.use(express.urlencoded({ extended: true, limit: bodyLimit }));
app.use(activityLogger);
app.use('/images', express.static(path.join(publicPath, 'images')));
app.use('/videos', express.static(path.join(publicPath, 'videos')));

app.get('/api/health', async (req, res) => {
  const dbCharset = await getDbCharsetInfo();
  res.json({
    status: 'ok',
    service: 'autopost-backend',
    scheduler: process.env.DISABLE_SCHEDULER !== 'true',
    media_storage: getMediaStorageMode(),
    db_charset: dbCharset,
  });
});

app.use('/api/auth', authRoutes);
app.use('/api/users', usersRoutes);
app.use('/api/providers', providersRoutes);
app.use('/api/pages', pagesRoutes);
app.use('/api/websites', websitesRoutes);
app.use('/api/skills', skillsRoutes);
app.use('/api/posts', postsRoutes);
app.use('/api/jobs', jobsRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/activity', activityRoutes);
app.use('/api/upload', uploadRoutes);
app.use('/api/media', mediaRoutes);
app.use('/api/settings', settingsRoutes);
app.use('/api/group-posts', groupPostsRoutes);
app.use('/api/group-categories', groupCategoriesRoutes);
app.use('/api/drive', driveAuthRoutes);
app.use('/api/user-auth', userAuthRoutes);
// v1.0.221-backend — mọi route ở đây chỉ dùng bởi extension (authenticateLicenseKey), tự động gọi
// định kỳ vài phút/thiết bị + mỗi lần mở tab Comment/panel — không có giới hạn tốc độ nào trước đây
// (audit 2026-07-06, xem CHANGELOG), 1 license key lỗi vòng lặp có thể gọi vô hạn tốc độ dồn hết
// vào chung 1 MySQL pool với cả website admin.
app.use('/api/user-sync', syncApiLimiter, userSyncRoutes);

app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

app.use((err, req, res, next) => {
  console.error(err);
  if (err.type === 'entity.too.large') {
    return res.status(413).json({ error: 'File hoặc dữ liệu quá lớn — thử import file Excel trực tiếp hoặc giảm số dòng' });
  }
  const status = err.status || 500;
  const safeStatus = status === 401 && !String(req.originalUrl || '').includes('/auth') ? 400 : status;
  res.status(safeStatus).json({ error: err.message || 'Internal server error' });
});

app.listen(port, async () => {
  console.log(`AutoPost backend listening on http://localhost:${port}`);
  try {
    await ensureUserPagesTables();
  } catch (error) {
    console.warn('user_pages migration failed:', error.message);
    console.warn('Chạy thủ công: backend/migrations/001_user_pages.sql');
  }
  // Mỗi migration chạy ĐỘC LẬP trong try/catch riêng — trước đây tất cả nằm chung 1 try/catch tuần
  // tự, nên 1 migration ném lỗi là MỌI migration sau đó bị bỏ qua âm thầm (đã gặp: cột
  // group_post_drafts.category_ids không được thêm vì 1 migration phía trước lỗi → "Unknown column
  // 'd.category_ids'"). Giờ 1 cái lỗi chỉ log đúng tên nó, các cái còn lại vẫn chạy.
  const migrations = [
    ['ensurePageSkillsTable', ensurePageSkillsTable],
    ['ensureContentTopicsRepeatDaily', ensureContentTopicsRepeatDaily],
    ['ensureContentTopicsLastRun', ensureContentTopicsLastRun],
    ['ensureSkillsTypeColumn', ensureSkillsTypeColumn],
    ['ensureUsersUsernameColumn', ensureUsersUsernameColumn],
    ['ensurePostsFbMediaIds', ensurePostsFbMediaIds],
    ['ensurePostsAutoGenerateImage', ensurePostsAutoGenerateImage],
    ['ensurePostsSaveImageLocal', ensurePostsSaveImageLocal],
    ['ensurePostsAutoGenerateDefaultTrue', ensurePostsAutoGenerateDefaultTrue],
    ['ensureGeminiImageGenerateContent', ensureGeminiImageGenerateContent],
    ['ensure9RouterImageModel', ensure9RouterImageModel],
    ['ensurePostsPublishingStatus', ensurePostsPublishingStatus],
    ['ensureImageScheduleDb', ensureImageScheduleDb],
    ['ensureImageSchedulePerUser', ensureImageSchedulePerUser],
    ['ensurePageImageSchedule', ensurePageImageSchedule],
    ['ensureUtf8mb4TextColumns', ensureUtf8mb4TextColumns],
    ['ensureAppSettingsTable', ensureAppSettingsTable],
    ['ensureFbPagesComposio', ensureFbPagesComposio],
    ['ensureFbPagesDriveFolder', ensureFbPagesDriveFolder],
    ['ensureGroupPostsTables', ensureGroupPostsTables],
    ['ensureGroupPostDraftsTable', ensureGroupPostDraftsTable],
    ['ensureGroupPostNameSharedDrafts', ensureGroupPostNameSharedDrafts],
    ['ensureGroupPostClientSyncs', ensureGroupPostClientSyncs],
    ['ensureDriveOAuthMigration', ensureDriveOAuthMigration],
    ['ensurePostsPlatformPostType', ensurePostsPlatformPostType],
    ['ensureWebsitesTable', ensureWebsitesTable],
    ['ensurePostsWebsiteColumns', ensurePostsWebsiteColumns],
    ['ensureGroupPostsFbUrl', ensureGroupPostsFbUrl],
    ['ensureUserAccountsTable', ensureUserAccountsTable],
    ['ensureLicenseKeysTable', ensureLicenseKeysTable],
    ['ensureUserPostsTable', ensureUserPostsTable],
    ['ensureUserAccountsMergedIntoUsers', ensureUserAccountsMergedIntoUsers],
    ['ensureUserActivityLogTable', ensureUserActivityLogTable],
    ['ensureUserPostsUpdatedAt', ensureUserPostsUpdatedAt],
    ['ensureUserPostsMergedGroupPosts', ensureUserPostsMergedGroupPosts],
    ['ensureGroupPostDraftsSharedIndex', ensureGroupPostDraftsSharedIndex],
    ['ensureUserPostsPendingApproval', ensureUserPostsPendingApproval],
    ['ensureUserPostsCorrectUniqueKey', ensureUserPostsCorrectUniqueKey],
    ['ensureUsersPhone', ensureUsersPhone],
    ['ensureLicenseKeyDevices', ensureLicenseKeyDevices],
    ['ensureUserActivityLogAuthor', ensureUserActivityLogAuthor],
    ['ensureGroupPostCategories', ensureGroupPostCategories],
    ['ensureUserPostCategories', ensureUserPostCategories],
    ['ensureGroupPostDraftsCategory', ensureGroupPostDraftsCategory],
  ];
  for (const [name, fn] of migrations) {
    try {
      await fn();
    } catch (error) {
      console.warn(`Migration ${name} failed:`, error.message);
    }
  }
  try {
    await loadAppSettings();
  } catch (error) {
    console.warn('loadAppSettings failed:', error.message);
  }
  try {
    await seedProviderTemplates();
    await backfillProviderMetadata();
    console.log('AI provider templates ready');
  } catch (error) {
    console.warn('Provider templates seed skipped:', error.message);
    console.warn('Chạy backend/migrations/002_provider_templates.sql nếu DB cũ thiếu bảng/cột');
  }
  startScheduler();
  if (isUsingGoogleDrive()) {
    console.log('Media storage: Google Drive (ảnh không lưu lâu trên VPS)');
  } else {
    console.log('Media storage: local VPS disk');
  }
});
