import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import authRoutes from './routes/auth.js';
import usersRoutes from './routes/users.js';
import providersRoutes from './routes/providers.js';
import pagesRoutes from './routes/pages.js';
import skillsRoutes from './routes/skills.js';
import postsRoutes from './routes/posts.js';
import jobsRoutes from './routes/jobs.js';
import notificationsRoutes from './routes/notifications.js';
import activityRoutes from './routes/activity.js';
import uploadRoutes from './routes/upload.js';
import mediaRoutes from './routes/media.js';
import settingsRoutes from './routes/settings.js';
import groupPostsRoutes from './routes/groupPosts.js';
import driveAuthRoutes from './routes/driveAuth.js';
import { activityLogger } from './middleware/activityLog.js';
import { getMediaStorageMode, isUsingGoogleDrive } from './services/mediaStorage.js';
import {
  backfillProviderMetadata,
  seedProviderTemplates,
} from './services/providerTemplateService.js';
import { loadAppSettings } from './services/appSettingsService.js';
import { ensureUserPagesTables, ensurePageSkillsTable, ensureContentTopicsRepeatDaily, ensureContentTopicsLastRun, ensureSkillsTypeColumn, ensureUsersUsernameColumn, ensurePostsFbMediaIds, ensurePostsAutoGenerateImage, ensurePostsSaveImageLocal, ensurePostsAutoGenerateDefaultTrue, ensureGeminiImageGenerateContent, ensure9RouterImageModel, ensurePostsPublishingStatus, ensureImageScheduleDb, ensureImageSchedulePerUser, ensurePageImageSchedule, ensureUtf8mb4TextColumns, ensureAppSettingsTable, ensureFbPagesComposio, ensureFbPagesDriveFolder, ensureGroupPostsTables, ensureGroupPostDraftsTable, ensureGroupPostNameSharedDrafts, ensureGroupPostClientSyncs, ensureDriveOAuthMigration, ensurePostsPlatformPostType } from './services/migrationRunner.js';
import { startScheduler } from './services/scheduler.js';
import { getDbCharsetInfo } from './db.js';

dotenv.config();

const app = express();
const port = process.env.PORT || 3001;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const publicPath = path.resolve(__dirname, '../../public');

app.use(cors());
const bodyLimit = process.env.JSON_BODY_LIMIT || '15mb';
app.use(express.json({ limit: bodyLimit }));
app.use(express.urlencoded({ extended: true, limit: bodyLimit }));
app.use(activityLogger);
app.use('/images', express.static(path.join(publicPath, 'images')));
app.use('/videos', express.static(path.join(publicPath, 'videos')));

app.get('/api/health', async (req, res) => {
  const dbCharset = await getDbCharsetInfo();
  res.json({
    status: 'ok',
    service: 'autopost-backend',
    scheduler: process.env.DISABLE_SCHEDULER !== 'true',
    media_storage: getMediaStorageMode(),
    db_charset: dbCharset,
  });
});

app.use('/api/auth', authRoutes);
app.use('/api/users', usersRoutes);
app.use('/api/providers', providersRoutes);
app.use('/api/pages', pagesRoutes);
app.use('/api/skills', skillsRoutes);
app.use('/api/posts', postsRoutes);
app.use('/api/jobs', jobsRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/activity', activityRoutes);
app.use('/api/upload', uploadRoutes);
app.use('/api/media', mediaRoutes);
app.use('/api/settings', settingsRoutes);
app.use('/api/group-posts', groupPostsRoutes);
app.use('/api/auth/drive', driveAuthRoutes);

app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

app.use((err, req, res, next) => {
  console.error(err);
  if (err.type === 'entity.too.large') {
    return res.status(413).json({ error: 'File hoặc dữ liệu quá lớn — thử import file Excel trực tiếp hoặc giảm số dòng' });
  }
  const status = err.status || 500;
  const safeStatus = status === 401 && !String(req.originalUrl || '').includes('/auth') ? 400 : status;
  res.status(safeStatus).json({ error: err.message || 'Internal server error' });
});

app.listen(port, async () => {
  console.log(`AutoPost backend listening on http://localhost:${port}`);
  try {
    await ensureUserPagesTables();
  } catch (error) {
    console.warn('user_pages migration failed:', error.message);
    console.warn('Chạy thủ công: backend/migrations/001_user_pages.sql');
  }
  try {
    await ensurePageSkillsTable();
    await ensureContentTopicsRepeatDaily();
    await ensureContentTopicsLastRun();
    await ensureSkillsTypeColumn();
    await ensureUsersUsernameColumn();
    await ensurePostsFbMediaIds();
    await ensurePostsAutoGenerateImage();
    await ensurePostsSaveImageLocal();
    await ensurePostsAutoGenerateDefaultTrue();
    await ensureGeminiImageGenerateContent();
    await ensure9RouterImageModel();
    await ensurePostsPublishingStatus();
    await ensureImageScheduleDb();
    await ensureImageSchedulePerUser();
    await ensurePageImageSchedule();
    await ensureUtf8mb4TextColumns();
    await ensureAppSettingsTable();
    await ensureFbPagesComposio();
    await ensureFbPagesDriveFolder();
    await ensureGroupPostsTables();
    await ensureGroupPostDraftsTable();
    await ensureGroupPostNameSharedDrafts();
    await ensureGroupPostClientSyncs();
    await ensureDriveOAuthMigration();
    await ensurePostsPlatformPostType();
    await loadAppSettings();
  } catch (error) {
    console.warn('DB migration failed:', error.message);
  }
  try {
    await seedProviderTemplates();
    await backfillProviderMetadata();
    console.log('AI provider templates ready');
  } catch (error) {
    console.warn('Provider templates seed skipped:', error.message);
    console.warn('Chạy backend/migrations/002_provider_templates.sql nếu DB cũ thiếu bảng/cột');
  }
  startScheduler();
  if (isUsingGoogleDrive()) {
    console.log('Media storage: Google Drive (ảnh không lưu lâu trên VPS)');
  } else {
    console.log('Media storage: local VPS disk');
  }
});
